language: bash
sudo: required

before_install:
    - sudo apt-get -qqy install openssh-client git-core gnupg curl rsync
    - sudo curl -sSL https://deb.nodesource.com/setup_8.x | bash -
    - sudo apt-get -qqy install nodejs
    - echo "" >> ./.env
    - echo $ENV_PREVIEW_FILE | base64 -di >> ./.env
    - echo "APP_VERSION=$CI_COMMIT_TAG" >> ./.env
    - set -o allexport; source .env; set +o allexport

script:
    - npm run build

deploy:
    skip_cleanup: true
    condition: ((tag =~ /^v\d+\.\d+\.\d+-preview\d+$/) AND (branch = develop) OR (branch = master))
    script:
        - eval $(ssh-agent -s)
        - echo "$SSH_PRIVATE_KEY" | base64 -di > sshkey
        - echo "" >> sshkey
        - cat sshkey | tr -d '\r' | ssh-add - > /dev/null
        - mkdir -p ~/.ssh
        - chmod 700 ~/.ssh
        - echo "$PRIVATE_HOST_KEY" | base64 -di > ~/.ssh/known_hosts
        - ssh openfing@openfing.fing.edu.uy 'rm -rf ~/openfing/preview; mkdir ~/openfing/preview'
        - rsync -vaz -e ssh dist/ openfing@openfing.fing.edu.uy:~/openfing/preview
