language: node_js

node_js:
    - 12.6.0

sudo: required

before_install:
    - sudo apt-get update
    - sudo apt-get -qqy install openssh-client git-core gnupg curl rsync
    - echo "" >> ./.env
    - echo $ENV_PREVIEW_FILE | base64 -di >> ./.env
    - echo "APP_VERSION=$CI_COMMIT_TAG" >> ./.env
    - set -o allexport; source .env; set +o allexport

script:
    - npm run build

deploy:
    provider: script
    skip_cleanup: true
    condition: ((tag =~ /^v\d+\.\d+\.\d+-preview\d+$/) AND ((branch = develop) OR (branch = master)))
    script: bash scripts/deploy.sh
