language: node_js

node_js:
    - 12.6.0

sudo: required

before_install:
    - sudo apt-get update
    - sudo apt-get -qqy install openssh-client git-core gnupg curl rsync
    - echo "" >> ./.env
    - echo $ENV_PREVIEW_FILE | base64 -di >> ./.env
    - echo "APP_VERSION=$CI_COMMIT_TAG" >> ./.env
    - set -o allexport; source .env; set +o allexport

script:
    - npm run build

before_deploy:
    - touch __deploy.sh
    - echo "eval \$\(ssh-agent -s)" >> __deploy.sh
    - echo "echo \"\$SSH_PRIVATE_KEY\" | base64 -di > sshkey" >> __deploy.sh
    - echo "echo \"\" >> sshkey" >> __deploy.sh
    - echo "cat sshkey | tr -d '\r' | ssh-add - > /dev/null" >> __deploy.sh
    - echo "mkdir -p ~/.ssh" >> __deploy.sh
    - echo "chmod 700 ~/.ssh" >> __deploy.sh
    - echo "echo \"\$PRIVATE_HOST_KEY\" | base64 -di > ~/.ssh/known_hosts" >> __deploy.sh
    - echo "ssh openfing@openfing.fing.edu.uy 'rm -rf ~/openfing/preview; mkdir ~/openfing/preview'" >> __deploy.sh
    - echo "rsync -vaz -e ssh dist/ openfing@openfing.fing.edu.uy:~/openfing/preview" >> __deploy.sh

deploy:
    - provider: script
      skip_cleanup: true
      condition: ((tag =~ /^v\d+\.\d+\.\d+-preview\d+$/) AND ((branch = develop) OR (branch = master)))
      script: ./__deploy.sh
